language: node_js

node_js: stable

install:
  - npm install

after_script:
  - cd ./public
  - git init
  - git config --global user.name "liujie"
  - git config --global user.email liujie@wilddog.com
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

script:
- hexo clean
- hexo generate

branches:
  only:
  - master

env:
 global:
   - GH_REF: github.com/liujie3612/liujie3612.github.io.git