language: node_js  #设置语言
node_js: stable  #设置相应的版本

# before_install:
# - npm install -g hexo
# - npm install -g hexo-cli

# install:
#   - npm install

script:
  # - hexo clean #清除
  - hexo clean && hexo g #生成

after_script:
  - hexo deploy

branches:
  only:
    - master