language: node_js  #设置语言

node_js: stable  #设置相应的版本

before_install:
- npm install -g hexo
- npm install -g hexo-cli

install:
  - npm install  #安装hexo及插件

script:
  # - hexo clean #清除
  - hexo clean && hexo g #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "liujie3612"  #修改name
  - git config user.email "liujie@wilddog.com"  #修改email
  - git add .
  - git commit -m "update"
  - git push  #GH_TOKEN是在Travis中配置token的名称
  - hexo deploy

branches:
  only:
    - master  #只监测hexo分支，hexo是我的分支的名称，可根据自己情况设置